### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by wxddegithub** [Skycoder42/QtMvvm#3]
Hello, there is a question when I build the QtMvvm with Qt Creator 5.9
'qpmx' 不是内部或外部命令，也不是可运行的程序
Project ERROR: qpmx initialization failed. Check the compilation log for details.

**Comment by Skycoder42** [comment]
Did you install all the build dependencies found in the readme? Especially qpmx? If yes, ensure that qpmx and qpm are in the PATH

**Comment by Skycoder42** [comment]
Also Qt 5.9 is not supported, as the QML-APIs used are only available from Qt 5.10 on.

**Comment by Skycoder42** [comment]
Can I close this issue?
